export const applications = [
  {
    id: 1,
    applicationId: "APPX7A9D2",
    userName: "Rohit Kumar",
    address: "123 MG Road, Bangalore",
    mobileNo: "+91 9876543210",
    email: "rohit.kumar@example.com",
    applicationDate: "2025-08-01",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Ajay Singh",
      assignedDate: "2025-08-05",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 2,
    applicationId: "APPU3K4F8",
    userName: "Sneha Sharma",
    address: "45 Park Street, Kolkata",
    mobileNo: "+91 9123456789",
    email: "sneha.sharma@example.com",
    applicationDate: "2025-08-02",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Ravi Kumar",
      assignedDate: "2025-08-06",
      visitDate: "2025-08-08",
      verificationStatus: "Verified",
      remarks: "Residence and office address verified successfully",
    },
  },
  {
    id: 3,
    applicationId: "APPZ9L3K1",
    userName: "Amit Verma",
    address: "12 Sector 14, Gurgaon",
    mobileNo: "+91 9876501234",
    email: "amit.verma@example.com",
    applicationDate: "2025-08-03",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Sunil Mehta",
      assignedDate: "2025-08-07",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 4,
    applicationId: "APPA7M9K5",
    userName: "Priya Nair",
    address: "78 Marine Drive, Mumbai",
    mobileNo: "+91 9988776655",
    email: "priya.nair@example.com",
    applicationDate: "2025-08-04",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Rajesh Gupta",
      assignedDate: "2025-08-08",
      visitDate: "2025-08-10",
      verificationStatus: "Verified",
      remarks: "All documents matched and verified",
    },
  },
  {
    id: 5,
    applicationId: "APPH6B2P9",
    userName: "Karan Malhotra",
    address: "56 Civil Lines, Delhi",
    mobileNo: "+91 9811122233",
    email: "karan.malhotra@example.com",
    applicationDate: "2025-08-05",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Anil Yadav",
      assignedDate: "2025-08-09",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 6,
    applicationId: "APPT2L5G7",
    userName: "Neha Reddy",
    address: "90 Banjara Hills, Hyderabad",
    mobileNo: "+91 9900112233",
    email: "neha.reddy@example.com",
    applicationDate: "2025-08-06",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Vikram Singh",
      assignedDate: "2025-08-10",
      visitDate: "2025-08-12",
      verificationStatus: "Verified",
      remarks: "Residence verified, workplace unverified due to closure",
    },
  },
  {
    id: 7,
    applicationId: "APPD8J4Q1",
    userName: "Arjun Mehra",
    address: "10 Andheri East, Mumbai",
    mobileNo: "+91 9812233445",
    email: "arjun.mehra@example.com",
    applicationDate: "2025-08-07",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Deepak Sharma",
      assignedDate: "2025-08-11",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 8,
    applicationId: "APPM3V2C6",
    userName: "Simran Kaur",
    address: "55 Chandigarh Sector 17",
    mobileNo: "+91 9876678901",
    email: "simran.kaur@example.com",
    applicationDate: "2025-08-08",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Manoj Tiwari",
      assignedDate: "2025-08-12",
      visitDate: "2025-08-14",
      verificationStatus: "Verified",
      remarks: "All details checked and confirmed",
    },
  },
  {
    id: 9,
    applicationId: "APPK7R1F5",
    userName: "Vikas Sharma",
    address: "67 Rajouri Garden, Delhi",
    mobileNo: "+91 9815567890",
    email: "vikas.sharma@example.com",
    applicationDate: "2025-08-09",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Harish Chauhan",
      assignedDate: "2025-08-13",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 10,
    applicationId: "APPA5T8W9",
    userName: "Ananya Joshi",
    address: "34 Jayanagar, Bangalore",
    mobileNo: "+91 9123459876",
    email: "ananya.joshi@example.com",
    applicationDate: "2025-08-10",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Suresh Patil",
      assignedDate: "2025-08-14",
      visitDate: "2025-08-16",
      verificationStatus: "Verified",
      remarks: "Residence verified, workplace address mismatch",
    },
  },
  // ---------- More Records till 31 ----------
  {
    id: 11,
    applicationId: "APPF2X8C1",
    userName: "Manish Tiwari",
    address: "22 Connaught Place, Delhi",
    mobileNo: "+91 9817788990",
    email: "manish.tiwari@example.com",
    applicationDate: "2025-08-11",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Ramesh Yadav",
      assignedDate: "2025-08-15",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 12,
    applicationId: "APPJ6B5M9",
    userName: "Meena Agarwal",
    address: "5 Park Lane, Lucknow",
    mobileNo: "+91 9123456678",
    email: "meena.agarwal@example.com",
    applicationDate: "2025-08-12",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Sanjay Kapoor",
      assignedDate: "2025-08-16",
      visitDate: "2025-08-18",
      verificationStatus: "Verified",
      remarks: "Residence verified successfully",
    },
  },
  {
    id: 13,
    applicationId: "APPQ9L7D2",
    userName: "Rajeev Sinha",
    address: "88 Salt Lake, Kolkata",
    mobileNo: "+91 9813344556",
    email: "rajeev.sinha@example.com",
    applicationDate: "2025-08-13",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Deepak Yadav",
      assignedDate: "2025-08-17",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 14,
    applicationId: "APPU2D6V7",
    userName: "Aisha Khan",
    address: "45 Charminar, Hyderabad",
    mobileNo: "+91 9819988776",
    email: "aisha.khan@example.com",
    applicationDate: "2025-08-14",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Harsh Gupta",
      assignedDate: "2025-08-18",
      visitDate: "2025-08-20",
      verificationStatus: "Verified",
      remarks: "Workplace address verified",
    },
  },
  {
    id: 15,
    applicationId: "APPB5N8C2",
    userName: "Sandeep Kumar",
    address: "77 Hitech City, Hyderabad",
    mobileNo: "+91 9815567123",
    email: "sandeep.kumar@example.com",
    applicationDate: "2025-08-15",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Arvind Mishra",
      assignedDate: "2025-08-19",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 16,
    applicationId: "APPW8Z5J6",
    userName: "Divya Menon",
    address: "20 MG Road, Kochi",
    mobileNo: "+91 9877788990",
    email: "divya.menon@example.com",
    applicationDate: "2025-08-16",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Sameer Patel",
      assignedDate: "2025-08-20",
      visitDate: "2025-08-22",
      verificationStatus: "Verified",
      remarks: "All details verified",
    },
  },
  {
    id: 17,
    applicationId: "APPL3T9K2",
    userName: "Rajat Kapoor",
    address: "45 Sector 62, Noida",
    mobileNo: "+91 9814456677",
    email: "rajat.kapoor@example.com",
    applicationDate: "2025-08-17",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Mohit Sharma",
      assignedDate: "2025-08-21",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 18,
    applicationId: "APPM9C4B7",
    userName: "Rina Das",
    address: "11 Park Circus, Kolkata",
    mobileNo: "+91 9811237788",
    email: "rina.das@example.com",
    applicationDate: "2025-08-18",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Kunal Verma",
      assignedDate: "2025-08-22",
      visitDate: "2025-08-24",
      verificationStatus: "Verified",
      remarks: "Residence verified",
    },
  },
  {
    id: 19,
    applicationId: "APPR6J2T8",
    userName: "Anil Chauhan",
    address: "33 Rajendra Nagar, Indore",
    mobileNo: "+91 9815678890",
    email: "anil.chauhan@example.com",
    applicationDate: "2025-08-19",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Rohit Mehta",
      assignedDate: "2025-08-23",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 20,
    applicationId: "APPA4V9B3",
    userName: "Shweta Pandey",
    address: "90 Gomti Nagar, Lucknow",
    mobileNo: "+91 9819981234",
    email: "shweta.pandey@example.com",
    applicationDate: "2025-08-20",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Ashish Khanna",
      assignedDate: "2025-08-24",
      visitDate: "2025-08-26",
      verificationStatus: "Verified",
      remarks: "Office and residence matched",
    },
  },
  {
    id: 21,
    applicationId: "APPC7N6L2",
    userName: "Gaurav Jain",
    address: "66 Civil Lines, Jaipur",
    mobileNo: "+91 9812235678",
    email: "gaurav.jain@example.com",
    applicationDate: "2025-08-21",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Pankaj Kumar",
      assignedDate: "2025-08-25",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 22,
    applicationId: "APPU9T1D5",
    userName: "Kavya Iyer",
    address: "44 T Nagar, Chennai",
    mobileNo: "+91 9814458890",
    email: "kavya.iyer@example.com",
    applicationDate: "2025-08-22",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Naveen Rao",
      assignedDate: "2025-08-26",
      visitDate: "2025-08-28",
      verificationStatus: "Verified",
      remarks: "All documents verified",
    },
  },
  {
    id: 23,
    applicationId: "APPD5L2F8",
    userName: "Harsh Vardhan",
    address: "23 Green Park, Delhi",
    mobileNo: "+91 9813348890",
    email: "harsh.vardhan@example.com",
    applicationDate: "2025-08-23",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Siddharth Joshi",
      assignedDate: "2025-08-27",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 24,
    applicationId: "APPF8R6K3",
    userName: "Radhika Sharma",
    address: "67 JP Nagar, Bangalore",
    mobileNo: "+91 9812245789",
    email: "radhika.sharma@example.com",
    applicationDate: "2025-08-24",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Vikas Nair",
      assignedDate: "2025-08-28",
      visitDate: "2025-08-30",
      verificationStatus: "Verified",
      remarks: "Residence and office confirmed",
    },
  },
  {
    id: 25,
    applicationId: "APPL1V7D9",
    userName: "Akhil Raina",
    address: "55 Residency Road, Bangalore",
    mobileNo: "+91 9813346677",
    email: "akhil.raina@example.com",
    applicationDate: "2025-08-25",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Tarun Bhatia",
      assignedDate: "2025-08-29",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 26,
    applicationId: "APPT9M4B8",
    userName: "Shreya Sen",
    address: "90 Ballygunge, Kolkata",
    mobileNo: "+91 9815563344",
    email: "shreya.sen@example.com",
    applicationDate: "2025-08-26",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Rohit Kapoor",
      assignedDate: "2025-08-30",
      visitDate: "2025-09-01",
      verificationStatus: "Verified",
      remarks: "Details verified",
    },
  },
  {
    id: 27,
    applicationId: "APPM8R5K2",
    userName: "Nikhil Arora",
    address: "45 Sector 21, Chandigarh",
    mobileNo: "+91 9819982233",
    email: "nikhil.arora@example.com",
    applicationDate: "2025-08-27",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Manish Sharma",
      assignedDate: "2025-09-01",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 28,
    applicationId: "APPJ5C8N6",
    userName: "Anjali Gupta",
    address: "77 Sector 18, Noida",
    mobileNo: "+91 9811123344",
    email: "anjali.gupta@example.com",
    applicationDate: "2025-08-28",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Abhishek Yadav",
      assignedDate: "2025-09-02",
      visitDate: "2025-09-04",
      verificationStatus: "Verified",
      remarks: "Residence confirmed",
    },
  },
  {
    id: 29,
    applicationId: "APPC4V7L1",
    userName: "Aditya Narayan",
    address: "90 Lalbagh, Lucknow",
    mobileNo: "+91 9817783344",
    email: "aditya.narayan@example.com",
    applicationDate: "2025-08-29",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Rahul Jain",
      assignedDate: "2025-09-03",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  },
  {
    id: 30,
    applicationId: "APPN6B2K7",
    userName: "Pooja Sethi",
    address: "66 Gariahat, Kolkata",
    mobileNo: "+91 9818899900",
    email: "pooja.sethi@example.com",
    applicationDate: "2025-08-30",
    status: "FI Completed",
    userType: "Customer",
    fiDetails: {
      investigatorName: "Suresh Raina",
      assignedDate: "2025-09-04",
      visitDate: "2025-09-06",
      verificationStatus: "Verified",
      remarks: "All verified",
    },
  },
  {
    id: 31,
    applicationId: "APPU1T9L5",
    userName: "Rahul Deshmukh",
    address: "23 FC Road, Pune",
    mobileNo: "+91 9812237788",
    email: "rahul.deshmukh@example.com",
    applicationDate: "2025-08-31",
    status: "FI Pending",
    userType: "Retailer",
    fiDetails: {
      investigatorName: "Varun Malhotra",
      assignedDate: "2025-09-05",
      visitDate: null,
      verificationStatus: "Pending",
      remarks: "",
    },
  }
];
