export const credit = [
  {
    id: 1,
    applicationId: "APP-2024-00087",
    userType: "customer",
    name: "Amit Sharma",
    loanType: "Personal Loan",
    amountApplied: 500000,
    tenureMonths: 48,
    incomeMonthly: 75000,
    fixedObligationsMonthly: 25000,
    applicationDate: "2024-08-01",
    fiDate: "2024-08-05",
    creditAnalysisDate: "2024-08-08",
    creditAnalysisStatus: "verified",
    employment: {
      type: "Salaried",
      company: "Tech Mahindra",
      experienceYears: 5,
    },
    bankAccounts: [
      {
        bankName: "SBI",
        accountNumber: "XXXXXXXX1234",
        ifscCode: "SBIN0000456",
        branchCode: "0456",
        branchName: "Mumbai Main Branch",
        accountType: "Salary",
        currentBalance: 60000,
        avgBalance: 50000,
        avgInflow: 80000,
        avgOutflow: 70000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 720,
      utilization: 32,
      onTimeEMIRatio: 95,
    },
    bureau: {
      historyYears: 6,
      activeLines: [
        {
          type: "Credit Card",
          organization: "SBI",
          limit: 150000,
          balance: 45000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 5000, paidOnTime: true },
            { month: "2024-02", emiAmount: 5000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 5000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 5000, paidOnTime: true },
            { month: "2024-05", emiAmount: 5000, paidOnTime: true },
            { month: "2024-06", emiAmount: 5000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 5000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 5000, paidOnTime: true },
            { month: "2024-09", emiAmount: 5000, paidOnTime: true },
            { month: "2024-10", emiAmount: 5000, paidOnTime: true },
            { month: "2024-11", emiAmount: 5000, paidOnTime: true },
            { month: "2024-12", emiAmount: 5000, paidOnTime: true },
            { month: "2025-01", emiAmount: 5000, paidOnTime: true },
            { month: "2025-02", emiAmount: 5000, paidOnTime: true },
            { month: "2025-03", emiAmount: 5000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 5000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 5000, paidOnTime: true },
            { month: "2025-06", emiAmount: 5000, paidOnTime: true },
            { month: "2025-07", emiAmount: 5000, paidOnTime: true },
            { month: "2025-08", emiAmount: 5000, paidOnTime: true },
          ],
        },
        {
          type: "Two-Wheeler Loan",
          organization: "Bajaj Fin",
          limit: 0,
          balance: 80000,
          status: "Active",
          dpd: 2,
          emiHistory: [
            { month: "2024-01", emiAmount: 3000, paidOnTime: true },
            { month: "2024-02", emiAmount: 3000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 3000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 3000, paidOnTime: true },
            { month: "2024-05", emiAmount: 3000, paidOnTime: true },
            { month: "2024-06", emiAmount: 3000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 3000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 3000, paidOnTime: true },
            { month: "2024-09", emiAmount: 3000, paidOnTime: true },
            { month: "2024-10", emiAmount: 3000, paidOnTime: true },
            { month: "2024-11", emiAmount: 3000, paidOnTime: true },
            { month: "2024-12", emiAmount: 3000, paidOnTime: true },
            { month: "2025-01", emiAmount: 3000, paidOnTime: true },
            { month: "2025-02", emiAmount: 3000, paidOnTime: true },
            { month: "2025-03", emiAmount: 3000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 3000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 3000, paidOnTime: true },
            { month: "2025-06", emiAmount: 3000, paidOnTime: true },
            { month: "2025-07", emiAmount: 3000, paidOnTime: true },
            { month: "2025-08", emiAmount: 3000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 3,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Salary Slip (3M)", status: "pending" },
      { name: "Bank Statement (6M)", status: "verified" },
    ],
  },
  {
    id: 2,
    applicationId: "APP-2024-00088",
    userType: "customer",
    name: "Priya Verma",
    loanType: "Home Loan",
    amountApplied: 3000000,
    tenureMonths: 240,
    incomeMonthly: 120000,
    fixedObligationsMonthly: 45000,
    applicationDate: "2024-08-02",
    fiDate: "2024-08-06",
    creditAnalysisDate: "2024-08-09",
    creditAnalysisStatus: "in-progress",
    employment: {
      type: "Salaried",
      company: "FinEdge Solutions",
      experienceYears: 7,
    },
    bankAccounts: [
      {
        bankName: "HDFC Bank",
        accountNumber: "XXXXXXXX9988",
        ifscCode: "HDFC0000123",
        branchCode: "0123",
        branchName: "Noida Sector 18 Branch",
        accountType: "Salary",
        currentBalance: 85000,
        avgBalance: 72000,
        avgInflow: 125000,
        avgOutflow: 110000,
        redFlags: [],
      },
      {
        bankName: "Axis Bank",
        accountNumber: "XXXXXXXX1122",
        ifscCode: "UTIB0000678",
        branchCode: "0678",
        branchName: "Noida Sector 62 Branch",
        accountType: "Savings",
        currentBalance: 45000,
        avgBalance: 38000,
        avgInflow: 40000,
        avgOutflow: 35000,
        redFlags: ["High cash withdrawals"],
      },
    ],
    cibil: {
      score: 765,
      utilization: 28,
      onTimeEMIRatio: 98,
    },
    bureau: {
      historyYears: 8,
      activeLines: [
        {
          type: "Credit Card",
           organization: "Axis Bank",
          limit: 200000,
          balance: 50000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 6000, paidOnTime: true },
            { month: "2024-02", emiAmount: 6000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 6000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 6000, paidOnTime: true },
            { month: "2024-05", emiAmount: 6000, paidOnTime: true },
            { month: "2024-06", emiAmount: 6000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 6000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 6000, paidOnTime: true },
            { month: "2024-09", emiAmount: 6000, paidOnTime: true },
            { month: "2024-10", emiAmount: 6000, paidOnTime: true },
            { month: "2024-11", emiAmount: 6000, paidOnTime: true },
            { month: "2024-12", emiAmount: 6000, paidOnTime: true },
            { month: "2025-01", emiAmount: 6000, paidOnTime: true },
            { month: "2025-02", emiAmount: 6000, paidOnTime: true },
            { month: "2025-03", emiAmount: 6000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 6000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 6000, paidOnTime: true },
            { month: "2025-06", emiAmount: 6000, paidOnTime: true },
            { month: "2025-07", emiAmount: 6000, paidOnTime: true },
            { month: "2025-08", emiAmount: 6000, paidOnTime: true },
          ],
        },
        {
          type: "Car Loan",
          organization: "Bajaj Fin",
          limit: 0,
          balance: 250000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 12000, paidOnTime: true },
            { month: "2024-02", emiAmount: 12000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 12000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 12000, paidOnTime: true },
            { month: "2024-05", emiAmount: 12000, paidOnTime: true },
            { month: "2024-06", emiAmount: 12000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 12000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 12000, paidOnTime: true },
            { month: "2024-09", emiAmount: 12000, paidOnTime: true },
            { month: "2024-10", emiAmount: 12000, paidOnTime: true },
            { month: "2024-11", emiAmount: 12000, paidOnTime: true },
            { month: "2024-12", emiAmount: 12000, paidOnTime: true },
            { month: "2025-01", emiAmount: 12000, paidOnTime: true },
            { month: "2025-02", emiAmount: 12000, paidOnTime: true },
            { month: "2025-03", emiAmount: 12000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 12000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 12000, paidOnTime: true },
            { month: "2025-06", emiAmount: 12000, paidOnTime: true },
            { month: "2025-07", emiAmount: 12000, paidOnTime: true },
            { month: "2025-08", emiAmount: 12000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 2,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Property Papers", status: "pending" },
      { name: "Bank Statement (12M)", status: "verified" },
    ],
  },
  {
    id: 3,
    applicationId: "APP-2024-00089",
    userType: "customer",
    name: "Rohit Nair",
    loanType: "Car Loan",
    amountApplied: 800000,
    tenureMonths: 60,
    incomeMonthly: 65000,
    fixedObligationsMonthly: 20000,
    applicationDate: "2024-08-03",
    fiDate: "2024-08-07",
    creditAnalysisDate: "2024-08-10",
    creditAnalysisStatus: "verified",
    employment: {
      type: "Salaried",
      company: "BrightWorks Pvt Ltd",
      experienceYears: 5,
    },
    bankAccounts: [
      {
        bankName: "SBI",
        accountNumber: "XXXXXXXX2244",
        ifscCode: "SBIN0000567",
        branchCode: "0567",
        branchName: "Bandra Branch",
        accountType: "Salary",
        currentBalance: 60000,
        avgBalance: 48000,
        avgInflow: 70000,
        avgOutflow: 65000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 710,
      utilization: 40,
      onTimeEMIRatio: 92,
    },
    bureau: {
      historyYears: 5,
      activeLines: [
        {
          type: "Credit Card",
          organization: "SBI",
          limit: 100000,
          balance: 20000,
          status: "Active",
          dpd: 5,
          emiHistory: [
            { month: "2024-01", emiAmount: 4000, paidOnTime: true },
            { month: "2024-02", emiAmount: 4000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 4000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 4000, paidOnTime: true },
            { month: "2024-05", emiAmount: 4000, paidOnTime: true },
            { month: "2024-06", emiAmount: 4000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 4000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 4000, paidOnTime: true },
            { month: "2024-09", emiAmount: 4000, paidOnTime: true },
            { month: "2024-10", emiAmount: 4000, paidOnTime: true },
            { month: "2024-11", emiAmount: 4000, paidOnTime: true },
            { month: "2024-12", emiAmount: 4000, paidOnTime: true },
            { month: "2025-01", emiAmount: 4000, paidOnTime: true },
            { month: "2025-02", emiAmount: 4000, paidOnTime: true },
            { month: "2025-03", emiAmount: 4000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 4000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 4000, paidOnTime: true },
            { month: "2025-06", emiAmount: 4000, paidOnTime: true },
            { month: "2025-07", emiAmount: 4000, paidOnTime: true },
            { month: "2025-08", emiAmount: 4000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 1,
      inquiriesLast6m: 4,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Address Proof", status: "verified" },
      { name: "Car Quotation", status: "pending" },
    ],
  },
  {
    id: 4,
    applicationId: "APP-2024-00090",
    userType: "customer",
    name: "Meera Joshi",
    loanType: "Education Loan",
    amountApplied: 1500000,
    tenureMonths: 84,
    incomeMonthly: 40000,
    fixedObligationsMonthly: 12000,
    applicationDate: "2024-08-04",
    fiDate: "2024-08-08",
    creditAnalysisDate: "2024-08-11",
    creditAnalysisStatus: "verified",
    employment: {
      type: "Self-Employed",
      company: "Freelance Graphic Designer",
      experienceYears: 3,
    },
    bankAccounts: [
      {
        bankName: "ICICI Bank",
        accountNumber: "XXXXXXXX3344",
        ifscCode: "ICIC0000456",
        branchCode: "0456",
        branchName: "Pune Camp Branch",
        accountType: "Savings",
        currentBalance: 35000,
        avgBalance: 30000,
        avgInflow: 45000,
        avgOutflow: 40000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 685,
      utilization: 36,
      onTimeEMIRatio: 90,
    },
    bureau: {
      historyYears: 4,
      activeLines: [
        {
          type: "Credit Card",
          organization: "ICICI Bank",
          limit: 75000,
          balance: 30000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 2500, paidOnTime: true },
            { month: "2024-02", emiAmount: 2500, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 2500,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 2500, paidOnTime: true },
            { month: "2024-05", emiAmount: 2500, paidOnTime: true },
            { month: "2024-06", emiAmount: 2500, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 2500,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 2500, paidOnTime: true },
            { month: "2024-09", emiAmount: 2500, paidOnTime: true },
            { month: "2024-10", emiAmount: 2500, paidOnTime: true },
            { month: "2024-11", emiAmount: 2500, paidOnTime: true },
            { month: "2024-12", emiAmount: 2500, paidOnTime: true },
            { month: "2025-01", emiAmount: 2500, paidOnTime: true },
            { month: "2025-02", emiAmount: 2500, paidOnTime: true },
            { month: "2025-03", emiAmount: 2500, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 2500,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 2500, paidOnTime: true },
            { month: "2025-06", emiAmount: 2500, paidOnTime: true },
            { month: "2025-07", emiAmount: 2500, paidOnTime: true },
            { month: "2025-08", emiAmount: 2500, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 2,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Admission Letter", status: "pending" },
      { name: "Bank Statement (6M)", status: "verified" },
    ],
  },
  {
    id: 5,
    applicationId: "APP-2024-00091",
    userType: "customer",
    name: "Kunal Mehta",
    loanType: "Business Loan",
    amountApplied: 2500000,
    tenureMonths: 120,
    incomeMonthly: 200000,
    fixedObligationsMonthly: 80000,
    applicationDate: "2024-08-05",
    fiDate: "2024-08-09",
    creditAnalysisDate: "2024-08-12",
    creditAnalysisStatus: "pending",
    employment: {
      type: "Self-Employed",
      company: "Mehta Traders",
      experienceYears: 12,
    },
    bankAccounts: [
      {
        bankName: "Axis Bank",
        accountNumber: "XXXXXXXX7788",
        ifscCode: "UTIB0000789",
        branchCode: "0789",
        branchName: "Ahmedabad Main Branch",
        accountType: "Current",
        currentBalance: 150000,
        avgBalance: 120000,
        avgInflow: 250000,
        avgOutflow: 200000,
        redFlags: ["Frequent overdrafts"],
      },
      {
        bankName: "HDFC Bank",
        accountNumber: "XXXXXXXX8899",
        ifscCode: "HDFC0000678",
        branchCode: "0678",
        branchName: "CG Road Branch",
        accountType: "Savings",
        currentBalance: 90000,
        avgBalance: 70000,
        avgInflow: 80000,
        avgOutflow: 75000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 702,
      utilization: 45,
      onTimeEMIRatio: 88,
    },
    bureau: {
      historyYears: 10,
      activeLines: [
        {
          type: "Business Loan",
          organization: "Bajaj Fin",
          limit: 0,
          balance: 600000,
          status: "Active",
          dpd: 15,
          emiHistory: [
            { month: "2024-01", emiAmount: 25000, paidOnTime: true },
            { month: "2024-02", emiAmount: 25000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 25000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 25000, paidOnTime: true },
            { month: "2024-05", emiAmount: 25000, paidOnTime: true },
            { month: "2024-06", emiAmount: 25000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 25000,
              paidOnTime: false,
              delayDays: 15,
            },
            { month: "2024-08", emiAmount: 25000, paidOnTime: true },
            { month: "2024-09", emiAmount: 25000, paidOnTime: true },
            { month: "2024-10", emiAmount: 25000, paidOnTime: true },
            { month: "2024-11", emiAmount: 25000, paidOnTime: true },
            { month: "2024-12", emiAmount: 25000, paidOnTime: true },
            { month: "2025-01", emiAmount: 25000, paidOnTime: true },
            { month: "2025-02", emiAmount: 25000, paidOnTime: true },
            { month: "2025-03", emiAmount: 25000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 25000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 25000, paidOnTime: true },
            { month: "2025-06", emiAmount: 25000, paidOnTime: true },
            { month: "2025-07", emiAmount: 25000, paidOnTime: true },
            { month: "2025-08", emiAmount: 25000, paidOnTime: true },
          ],
        },
        {
          type: "Credit Card",
          organization: "HDFC Bank",
          limit: 300000,
          balance: 120000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 10000, paidOnTime: true },
            { month: "2024-02", emiAmount: 10000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 10000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 10000, paidOnTime: true },
            { month: "2024-05", emiAmount: 10000, paidOnTime: true },
            { month: "2024-06", emiAmount: 10000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 10000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 10000, paidOnTime: true },
            { month: "2024-09", emiAmount: 10000, paidOnTime: true },
            { month: "2024-10", emiAmount: 10000, paidOnTime: true },
            { month: "2024-11", emiAmount: 10000, paidOnTime: true },
            { month: "2024-12", emiAmount: 10000, paidOnTime: true },
            { month: "2025-01", emiAmount: 10000, paidOnTime: true },
            { month: "2025-02", emiAmount: 10000, paidOnTime: true },
            { month: "2025-03", emiAmount: 10000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 10000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 10000, paidOnTime: true },
            { month: "2025-06", emiAmount: 10000, paidOnTime: true },
            { month: "2025-07", emiAmount: 10000, paidOnTime: true },
            { month: "2025-08", emiAmount: 10000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 1,
      inquiriesLast6m: 5,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "GST Certificate", status: "verified" },
      { name: "Address Proof", status: "pending" },
      { name: "IT Returns (2Y)", status: "verified" },
    ],
  },
  {
    id: 6,
    applicationId: "APP-2024-00092",
    userType: "customer",
    name: "Sneha Kapoor",
    loanType: "Gold Loan",
    amountApplied: 300000,
    tenureMonths: 24,
    incomeMonthly: 50000,
    fixedObligationsMonthly: 15000,
    applicationDate: "2024-08-06",
    fiDate: "2024-08-10",
    creditAnalysisDate: "2024-08-13",
    creditAnalysisStatus: "verified",
    employment: {
      type: "Salaried",
      company: "Zenith Tech",
      experienceYears: 2,
    },
    bankAccounts: [
      {
        bankName: "Kotak Mahindra Bank",
        accountNumber: "XXXXXXXX4455",
        ifscCode: "KKBK0000234",
        branchCode: "0234",
        branchName: "Chandigarh Sector 17 Branch",
        accountType: "Savings",
        currentBalance: 25000,
        avgBalance: 22000,
        avgInflow: 48000,
        avgOutflow: 45000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 742,
      utilization: 25,
      onTimeEMIRatio: 97,
    },
    bureau: {
      historyYears: 3,
      activeLines: [
        {
          type: "Credit Card",
          organization: "Kotak Mahindra Bank",
          limit: 60000,
          balance: 15000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 2000, paidOnTime: true },
            { month: "2024-02", emiAmount: 2000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 2000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 2000, paidOnTime: true },
            { month: "2024-05", emiAmount: 2000, paidOnTime: true },
            { month: "2024-06", emiAmount: 2000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 2000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 2000, paidOnTime: true },
            { month: "2024-09", emiAmount: 2000, paidOnTime: true },
            { month: "2024-10", emiAmount: 2000, paidOnTime: true },
            { month: "2024-11", emiAmount: 2000, paidOnTime: true },
            { month: "2024-12", emiAmount: 2000, paidOnTime: true },
            { month: "2025-01", emiAmount: 2000, paidOnTime: true },
            { month: "2025-02", emiAmount: 2000, paidOnTime: true },
            { month: "2025-03", emiAmount: 2000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 2000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 2000, paidOnTime: true },
            { month: "2025-06", emiAmount: 2000, paidOnTime: true },
            { month: "2025-07", emiAmount: 2000, paidOnTime: true },
            { month: "2025-08", emiAmount: 2000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 1,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Gold Valuation Certificate", status: "pending" },
    ],
  },
  {
    id: 7,
    applicationId: "APP-2024-00093",
    userType: "customer",
    name: "Arjun Reddy",
    loanType: "Personal Loan",
    amountApplied: 700000,
    tenureMonths: 36,
    incomeMonthly: 90000,
    fixedObligationsMonthly: 30000,
    applicationDate: "2024-08-07",
    fiDate: "2024-08-11",
    creditAnalysisDate: "2024-08-14",
    creditAnalysisStatus: "verified",
    employment: {
      type: "Salaried",
      company: "Infosys",
      experienceYears: 6,
    },
    bankAccounts: [
      {
        bankName: "ICICI Bank",
        accountNumber: "XXXXXXXX5566",
        ifscCode: "ICIC0000345",
        branchCode: "0345",
        branchName: "Hyderabad Hitech City Branch",
        accountType: "Salary",
        currentBalance: 75000,
        avgBalance: 60000,
        avgInflow: 95000,
        avgOutflow: 85000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 755,
      utilization: 30,
      onTimeEMIRatio: 96,
    },
    bureau: {
      historyYears: 7,
      activeLines: [
        {
          type: "Credit Card",
          organization: "ICICI Bank",
          limit: 180000,
          balance: 60000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 5500, paidOnTime: true },
            { month: "2024-02", emiAmount: 5500, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 5500,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 5500, paidOnTime: true },
            { month: "2024-05", emiAmount: 5500, paidOnTime: true },
            { month: "2024-06", emiAmount: 5500, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 5500,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 5500, paidOnTime: true },
            { month: "2024-09", emiAmount: 5500, paidOnTime: true },
            { month: "2024-10", emiAmount: 5500, paidOnTime: true },
            { month: "2024-11", emiAmount: 5500, paidOnTime: true },
            { month: "2024-12", emiAmount: 5500, paidOnTime: true },
            { month: "2025-01", emiAmount: 5500, paidOnTime: true },
            { month: "2025-02", emiAmount: 5500, paidOnTime: true },
            { month: "2025-03", emiAmount: 5500, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 5500,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 5500, paidOnTime: true },
            { month: "2025-06", emiAmount: 5500, paidOnTime: true },
            { month: "2025-07", emiAmount: 5500, paidOnTime: true },
            { month: "2025-08", emiAmount: 5500, paidOnTime: true },
          ],
        },
        {
          type: "Two-Wheeler Loan",
          organization: "Bajaj Fin",
          limit: 0,
          balance: 60000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 3200, paidOnTime: true },
            { month: "2024-02", emiAmount: 3200, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 3200,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 3200, paidOnTime: true },
            { month: "2024-05", emiAmount: 3200, paidOnTime: true },
            { month: "2024-06", emiAmount: 3200, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 3200,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 3200, paidOnTime: true },
            { month: "2024-09", emiAmount: 3200, paidOnTime: true },
            { month: "2024-10", emiAmount: 3200, paidOnTime: true },
            { month: "2024-11", emiAmount: 3200, paidOnTime: true },
            { month: "2024-12", emiAmount: 3200, paidOnTime: true },
            { month: "2025-01", emiAmount: 3200, paidOnTime: true },
            { month: "2025-02", emiAmount: 3200, paidOnTime: true },
            { month: "2025-03", emiAmount: 3200, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 3200,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 3200, paidOnTime: true },
            { month: "2025-06", emiAmount: 3200, paidOnTime: true },
            { month: "2025-07", emiAmount: 3200, paidOnTime: true },
            { month: "2025-08", emiAmount: 3200, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 3,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Salary Slip (3M)", status: "verified" },
      { name: "Bank Statement (6M)", status: "pending" },
    ],
  },
  {
    id: 8,
    applicationId: "APP-2024-00094",
    userType: "customer",
    name: "Neha Singh",
    loanType: "Home Loan",
    amountApplied: 4500000,
    tenureMonths: 300,
    incomeMonthly: 150000,
    fixedObligationsMonthly: 60000,
    applicationDate: "2024-08-08",
    fiDate: "2024-08-12",
    creditAnalysisDate: "2024-08-15",
    creditAnalysisStatus: "in-progress",
    employment: {
      type: "Salaried",
      company: "Wipro",
      experienceYears: 9,
    },
    bankAccounts: [
      {
        bankName: "HDFC Bank",
        accountNumber: "XXXXXXXX6677",
        ifscCode: "HDFC0000890",
        branchCode: "0890",
        branchName: "Delhi Connaught Place Branch",
        accountType: "Salary",
        currentBalance: 100000,
        avgBalance: 85000,
        avgInflow: 155000,
        avgOutflow: 140000,
        redFlags: [],
      },
      {
        bankName: "SBI",
        accountNumber: "XXXXXXXX7788",
        ifscCode: "SBIN0000123",
        branchCode: "0123",
        branchName: "Delhi Main Branch",
        accountType: "Savings",
        currentBalance: 50000,
        avgBalance: 42000,
        avgInflow: 45000,
        avgOutflow: 40000,
        redFlags: [],
      },
    ],
    cibil: {
      score: 770,
      utilization: 20,
      onTimeEMIRatio: 99,
    },
    bureau: {
      historyYears: 12,
      activeLines: [
        {
          type: "Home Loan",
          organization: "Bajaj Fin",
          limit: 0,
          balance: 1200000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 35000, paidOnTime: true },
            { month: "2024-02", emiAmount: 35000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 35000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 35000, paidOnTime: true },
            { month: "2024-05", emiAmount: 35000, paidOnTime: true },
            { month: "2024-06", emiAmount: 35000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 35000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 35000, paidOnTime: true },
            { month: "2024-09", emiAmount: 35000, paidOnTime: true },
            { month: "2024-10", emiAmount: 35000, paidOnTime: true },
            { month: "2024-11", emiAmount: 35000, paidOnTime: true },
            { month: "2024-12", emiAmount: 35000, paidOnTime: true },
            { month: "2025-01", emiAmount: 35000, paidOnTime: true },
            { month: "2025-02", emiAmount: 35000, paidOnTime: true },
            { month: "2025-03", emiAmount: 35000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 35000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 35000, paidOnTime: true },
            { month: "2025-06", emiAmount: 35000, paidOnTime: true },
            { month: "2025-07", emiAmount: 35000, paidOnTime: true },
            { month: "2025-08", emiAmount: 35000, paidOnTime: true },
          ],
        },
        {
          type: "Credit Card",
            organization: "HDFC Bank",
          limit: 250000,
          balance: 80000,
          status: "Active",
          dpd: 0,
          emiHistory: [
            { month: "2024-01", emiAmount: 7000, paidOnTime: true },
            { month: "2024-02", emiAmount: 7000, paidOnTime: true },
            {
              month: "2024-03",
              emiAmount: 7000,
              paidOnTime: false,
              delayDays: 5,
            },
            { month: "2024-04", emiAmount: 7000, paidOnTime: true },
            { month: "2024-05", emiAmount: 7000, paidOnTime: true },
            { month: "2024-06", emiAmount: 7000, paidOnTime: true },
            {
              month: "2024-07",
              emiAmount: 7000,
              paidOnTime: false,
              delayDays: 8,
            },
            { month: "2024-08", emiAmount: 7000, paidOnTime: true },
            { month: "2024-09", emiAmount: 7000, paidOnTime: true },
            { month: "2024-10", emiAmount: 7000, paidOnTime: true },
            { month: "2024-11", emiAmount: 7000, paidOnTime: true },
            { month: "2024-12", emiAmount: 7000, paidOnTime: true },
            { month: "2025-01", emiAmount: 7000, paidOnTime: true },
            { month: "2025-02", emiAmount: 7000, paidOnTime: true },
            { month: "2025-03", emiAmount: 7000, paidOnTime: true },
            {
              month: "2025-04",
              emiAmount: 7000,
              paidOnTime: false,
              delayDays: 12,
            },
            { month: "2025-05", emiAmount: 7000, paidOnTime: true },
            { month: "2025-06", emiAmount: 7000, paidOnTime: true },
            { month: "2025-07", emiAmount: 7000, paidOnTime: true },
            { month: "2025-08", emiAmount: 7000, paidOnTime: true },
          ],
        },
      ],
      delinquencies: 0,
      inquiriesLast6m: 2,
    },
    documents: [
      { name: "PAN", status: "verified" },
      { name: "Aadhaar", status: "verified" },
      { name: "Property Papers", status: "pending" },
      { name: "Bank Statement (12M)", status: "verified" },
    ],
  },
];

//*********************8-9-25 5:44************************ */
// export const credit = [
//   {
//     id: 1,
//     applicationId: "APP-2024-00087",
//     userType: "customer",
//     name: "Aarav Sharma",
//     loanType: "Personal Loan",
//     amountApplied: 500000,
//     tenureMonths: 36,
//     incomeMonthly: 85000,
//     fixedObligationsMonthly: 32000,
//     applicationDate: "2024-08-01",
//     fiDate: "2024-08-05",
//     creditAnalysisDate: "2024-08-08",
//     creditAnalysisStatus: "verified",
//     employment: {
//       type: "Salaried",
//       company: "TechNova Pvt Ltd",
//       experienceYears: 4,
//     },
//     bankSummary: {
//       avgBalance: 42000,
//       avgInflow: 90000,
//       avgOutflow: 78000,
//       redFlags: ["2 cheque bounces in last 12 months"],
//     },
//     cibil: {
//       score: 738,
//       utilization: 31,
//       onTimeEMIRatio: 96,
//     },
//     bureau: {
//       historyYears: 6,
//       activeLines: [
//         { type: "Credit Card", limit: 150000, balance: 43000, status: "Active", dpd: 0 },
//         { type: "Two-Wheeler Loan", limit: 0, balance: 28000, status: "Closed", dpd: 0 },
//       ],
//       delinquencies: 0,
//       inquiriesLast6m: 3,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "Address Proof", status: "pending" },
//       { name: "Salary Slips (3M)", status: "verified" },
//       { name: "Bank Statement (6M)", status: "verified" },
//     ],
//   },
//   {
//     id: 2,
//     applicationId: "APP-2024-00088",
//     userType: "retailer",
//     businessType: "proprietorship",
//     name: "Neha Verma",
//     loanType: "Business Loan",
//     amountApplied: 1200000,
//     tenureMonths: 60,
//     incomeMonthly: 100000,
//     fixedObligationsMonthly: 40000,
//     applicationDate: "2024-08-03",
//     fiDate: "2024-08-07",
//     creditAnalysisDate: "2024-08-10",
//     creditAnalysisStatus: "verified",
//     employment: {
//       type: "Self-Employed",
//       company: "Neha Traders",
//       experienceYears: 6,
//     },
//     bankSummary: {
//       avgBalance: 95000,
//       avgInflow: 180000,
//       avgOutflow: 150000,
//       redFlags: [],
//     },
//     cibil: {
//       score: 725,
//       utilization: 27,
//       onTimeEMIRatio: 93,
//     },
//     bureau: {
//       historyYears: 7,
//       activeLines: [
//         { type: "Credit Card", limit: 200000, balance: 60000, status: "Active", dpd: 0 },
//         { type: "Business Loan", limit: 500000, balance: 120000, status: "Active", dpd: 5 },
//       ],
//       delinquencies: 1,
//       inquiriesLast6m: 4,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "GST Certificate", status: "verified" },
//       { name: "Shop Proof", status: "pending" },
//       { name: "Bank Statement (6M)", status: "verified" },
//     ],
//   },
//   {
//     id: 3,
//     applicationId: "APP-2024-00089",
//     userType: "retailer",
//     businessType: "partnership",
//     name: "Ravi Kumar",
//     loanType: "Business Loan",
//     amountApplied: 2200000,
//     tenureMonths: 72,
//     incomeMonthly: 180000,
//     fixedObligationsMonthly: 75000,
//     applicationDate: "2024-08-04",
//     fiDate: "2024-08-08",
//     creditAnalysisDate: "2024-08-12",
//     creditAnalysisStatus: "rejected",
//     employment: {
//       type: "Self-Employed",
//       company: "Kumar & Sons",
//       experienceYears: 11,
//     },
//     bankSummary: {
//       avgBalance: 30000,
//       avgInflow: 160000,
//       avgOutflow: 170000,
//       redFlags: ["Frequent overdrafts", "High outflow > inflow"],
//     },
//     cibil: {
//       score: 690,
//       utilization: 42,
//       onTimeEMIRatio: 87,
//     },
//     bureau: {
//       historyYears: 5,
//       activeLines: [
//         { type: "Credit Card", limit: 120000, balance: 80000, status: "Active", dpd: 12 },
//         { type: "Consumer Durable", limit: 50000, balance: 20000, status: "Active", dpd: 0 },
//       ],
//       delinquencies: 2,
//       inquiriesLast6m: 6,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "Partnership Deed", status: "verified" },
//       { name: "GST Certificate", status: "pending" },
//       { name: "Bank Statement (12M)", status: "verified" },
//     ],
//   },
//   {
//     id: 4,
//     applicationId: "APP-2024-00090",
//     userType: "retailer",
//     businessType: "private-limited",
//     name: "Simran Kaur",
//     loanType: "Business Loan",
//     amountApplied: 5000000,
//     tenureMonths: 120,
//     incomeMonthly: 300000,
//     fixedObligationsMonthly: 120000,
//     applicationDate: "2024-08-06",
//     fiDate: "2024-08-11",
//     creditAnalysisDate: "2024-08-15",
//     creditAnalysisStatus: "verified",
//     employment: {
//       type: "Self-Employed",
//       company: "Kaur Enterprises Pvt Ltd",
//       experienceYears: 9,
//     },
//     bankSummary: {
//       avgBalance: 220000,
//       avgInflow: 600000,
//       avgOutflow: 450000,
//       redFlags: [],
//     },
//     cibil: {
//       score: 745,
//       utilization: 30,
//       onTimeEMIRatio: 95,
//     },
//     bureau: {
//       historyYears: 8,
//       activeLines: [
//         { type: "Credit Card", limit: 500000, balance: 90000, status: "Active", dpd: 0 },
//         { type: "Car Loan", limit: 1200000, balance: 500000, status: "Active", dpd: 0 },
//       ],
//       delinquencies: 0,
//       inquiriesLast6m: 2,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "MOA/AOA", status: "pending" },
//       { name: "ROC Certificate", status: "verified" },
//       { name: "Bank Statement (12M)", status: "verified" },
//     ],
//   },
//   {
//     id: 5,
//     applicationId: "APP-2024-00091",
//     userType: "customer",
//     name: "Mohit Singh",
//     loanType: "Education Loan",
//     amountApplied: 800000,
//     tenureMonths: 120,
//     incomeMonthly: 0,
//     fixedObligationsMonthly: 0,
//     applicationDate: "2024-08-09",
//     fiDate: "2024-08-13",
//     creditAnalysisDate: "2024-08-18",
//     creditAnalysisStatus: "pending",
//     employment: {
//       type: "Student",
//       company: "",
//       experienceYears: 0,
//     },
//     bankSummary: {
//       avgBalance: 15000,
//       avgInflow: 10000,
//       avgOutflow: 8000,
//       redFlags: ["Low account activity"],
//     },
//     cibil: {
//       score: 702,
//       utilization: 15,
//       onTimeEMIRatio: 90,
//     },
//     bureau: {
//       historyYears: 2,
//       activeLines: [],
//       delinquencies: 0,
//       inquiriesLast6m: 1,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "Address Proof", status: "verified" },
//       { name: "Co-Applicant Docs", status: "pending" },
//     ],
//   },
//     {
//     id: 6,
//     applicationId: "APP-2024-00092",
//     userType: "customer",
//     name: "Priya Nair",
//     loanType: "Gold Loan",
//     amountApplied: 300000,
//     tenureMonths: 24,
//     incomeMonthly: 60000,
//     fixedObligationsMonthly: 15000,
//     applicationDate: "2024-08-12",
//     fiDate: "2024-08-16",
//     creditAnalysisDate: "2024-08-19",
//     creditAnalysisStatus: "verified",
//     employment: {
//       type: "Self-Employed",
//       company: "Boutique Owner",
//       experienceYears: 6,
//     },
//     bankSummary: {
//       avgBalance: 65000,
//       avgInflow: 75000,
//       avgOutflow: 62000,
//       redFlags: [],
//     },
//     cibil: {
//       score: 755,
//       utilization: 18,
//       onTimeEMIRatio: 97,
//     },
//     bureau: {
//       historyYears: 7,
//       activeLines: [
//         { type: "Credit Card", limit: 100000, balance: 25000, status: "Active", dpd: 0 },
//         { type: "Gold Loan", limit: 300000, balance: 100000, status: "Active", dpd: 0 },
//       ],
//       delinquencies: 0,
//       inquiriesLast6m: 2,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "Address Proof", status: "pending" },
//       { name: "Bank Statement (6M)", status: "verified" },
//     ],
//   },
//   {
//     id: 7,
//     applicationId: "APP-2024-00093",
//     userType: "retailer",
//     businessType: "proprietorship",
//     name: "Aditya Mehta",
//     loanType: "Business Loan",
//     amountApplied: 1800000,
//     tenureMonths: 48,
//     incomeMonthly: 120000,
//     fixedObligationsMonthly: 50000,
//     applicationDate: "2024-08-14",
//     fiDate: "2024-08-18",
//     creditAnalysisDate: "2024-08-21",
//     creditAnalysisStatus: "verified",
//     employment: {
//       type: "Self-Employed",
//       company: "Mehta Electronics",
//       experienceYears: 10,
//     },
//     bankSummary: {
//       avgBalance: 85000,
//       avgInflow: 210000,
//       avgOutflow: 170000,
//       redFlags: ["High cash deposits"],
//     },
//     cibil: {
//       score: 720,
//       utilization: 28,
//       onTimeEMIRatio: 94,
//     },
//     bureau: {
//       historyYears: 9,
//       activeLines: [
//         { type: "Credit Card", limit: 250000, balance: 75000, status: "Active", dpd: 0 },
//         { type: "Car Loan", limit: 800000, balance: 320000, status: "Active", dpd: 2 },
//       ],
//       delinquencies: 1,
//       inquiriesLast6m: 5,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "GST Certificate", status: "verified" },
//       { name: "Shop Proof", status: "verified" },
//       { name: "Bank Statement (6M)", status: "pending" },
//     ],
//   },
//   {
//     id: 8,
//     applicationId: "APP-2024-00094",
//     userType: "retailer",
//     businessType: "partnership",
//     name: "Kavya Reddy",
//     loanType: "Business Loan",
//     amountApplied: 2500000,
//     tenureMonths: 84,
//     incomeMonthly: 200000,
//     fixedObligationsMonthly: 85000,
//     applicationDate: "2024-08-17",
//     fiDate: "2024-08-20",
//     creditAnalysisDate: "2024-08-24",
//     creditAnalysisStatus: "pending",
//     employment: {
//       type: "Self-Employed",
//       company: "Reddy Associates",
//       experienceYears: 13,
//     },
//     bankSummary: {
//       avgBalance: 120000,
//       avgInflow: 350000,
//       avgOutflow: 280000,
//       redFlags: ["Irregular cash flow"],
//     },
//     cibil: {
//       score: 710,
//       utilization: 36,
//       onTimeEMIRatio: 92,
//     },
//     bureau: {
//       historyYears: 10,
//       activeLines: [
//         { type: "Credit Card", limit: 300000, balance: 100000, status: "Active", dpd: 0 },
//         { type: "Business Loan", limit: 2000000, balance: 950000, status: "Active", dpd: 8 },
//       ],
//       delinquencies: 2,
//       inquiriesLast6m: 6,
//     },
//     documents: [
//       { name: "PAN", status: "verified" },
//       { name: "Aadhaar", status: "verified" },
//       { name: "Partnership Deed", status: "pending" },
//       { name: "GST Certificate", status: "verified" },
//       { name: "Bank Statement (12M)", status: "verified" },
//     ],
//   },
// ];
