export const pdiData = [
  {
    id: 1,
    applicationId: "APP-2024-00087",
    userType: "customer",
    name: "Rahul Sharma",
    email: "rahul.sharma@example.com",
    phone: "+91-9876543210",
    address: "Delhi, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
  {
    id: 2,
    applicationId: "APP-2024-00088",
    userType: "retailer",
    name: "Priya Verma",
    email: "priya.verma@example.com",
    phone: "+91-9123456789",
    address: "Mumbai, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
  {
    id: 3,
    applicationId: "APP-2024-00089",
    userType: "customer",
    name: "Amit Kumar",
    email: "amit.kumar@example.com",
    phone: "+91-9811122233",
    address: "Bangalore, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
  {
    id: 4,
    applicationId: "APP-2024-00090",
    userType: "retailer",
    name: "Sneha Kapoor",
    email: "sneha.kapoor@example.com",
    phone: "+91-9822334455",
    address: "Chennai, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
  {
    id: 5,
    applicationId: "APP-2024-00091",
    userType: "customer",
    name: "Ravi Singh",
    email: "ravi.singh@example.com",
    phone: "+91-9833445566",
    address: "Kolkata, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
  {
    id: 6,
    applicationId: "APP-2024-00092",
    userType: "retailer",
    name: "Anjali Mehta",
    email: "anjali.mehta@example.com",
    phone: "+91-9844556677",
    address: "Hyderabad, India",
    questions: [
      {
        qid: 1,
        question: "Is the shop physically verified?",
        required: true,
        length: 50,
        supportedDocument: "Shop License",
      },
      {
        qid: 2,
        question: "Does the customer have a valid ID proof?",
        required: true,
        length: 20,
      },
      {
        qid: 3,
        question: "Has the income proof document been collected?",
        required: false,
        length: 100,
        supportedDocument: "Salary Slip",
      },
    ],
  },
];
